// Auto-generated by scripts/sync-audio-paths.mjs — do not edit by hand.
window.uiAudioPaths = {
  "spinButton": "audio/ui/spin/spin-projector-button-push.mp3",
  "spinIntroClips": [
    "audio/ui/intro/output.wav",
    "audio/ui/intro/output 2.wav",
    "audio/ui/intro/output 3.wav",
    "audio/ui/intro/output 4.wav",
    "audio/ui/intro/output 5.wav",
    "audio/ui/intro/output 7.wav",
    "audio/ui/intro/output 19.wav",
    "audio/ui/intro/output 21.wav",
    "audio/ui/intro/output 29.wav"
  ],
  "keeperClipsBySlotCount": {
    "1": [
      "audio/ui/keeper/keeper-kaching.mp3"
    ],
    "2": [
      "audio/ui/keeper/keeper-money-counting.mp3"
    ],
    "3": [
      "audio/ui/keeper/keeper-money-counting.mp3",
      "audio/ui/keeper/keeper-kaching.mp3",
      "audio/ui/keeper/keeper-jackpot-coins.mp3",
      "audio/ui/keeper/keeper-casino-counter.wav"
    ]
  },
  "keeperKaching": "audio/ui/keeper/keeper-kaching.mp3",
  "coinFlip1": "audio/ui/coin-flip/coin-flip-1.mp3",
  "coinFlip2": "audio/ui/coin-flip/coin-flip-2.mp3",
  "coinFlipSpinShort": "audio/ui/coin-flip/spinning coin shorter.mp3",
  "coinFlipSpinBedClips": [
    "audio/win/neon_skyline/HKE3.2.mp3",
    "audio/win/neon_skyline/HKE1.mp3",
    "audio/win/neon_skyline/HKE2.mp3",
    "audio/_staging/that-slow-motion-running-song-ii.mp3"
  ],
  "shuffleClips": [
    "audio/ui/shuffle/ticket-shuffle-crumple.mp3",
    "audio/ui/shuffle/ticket-shuffle-flap-loop.mp3",
    "audio/ui/shuffle/ticket-shuffle-crumble-alt.mp3"
  ],
  "shuffleIntroSfx": {
    "emerge": "audio/ui/shuffle/ticket-shuffle-crumple.mp3",
    "mystery": "audio/ui/shuffle/ticket-shuffle-crumble-alt.mp3",
    "rowAlign": "audio/ui/shuffle/ticket-shuffle-crumple.mp3",
    "stack": "audio/ui/shuffle/ticket-shuffle-crumple.mp3",
    "deploy": "audio/ui/shuffle/ticket-shuffle-crumble-alt.mp3",
    "flip": "audio/ui/shuffle/ticket-shuffle-crumble-alt.mp3"
  },
  "shuffleLockIn": "audio/ui/shuffle/fast woosh boom.mp3",
  "shuffleJokerWhoosh": "audio/ui/shuffle/joker whoosh.mp3",
  "shuffleGoldenTicket": "audio/ui/shuffle/current golden ticket1.mp3",
  "shuffleShortShuffle": "audio/ui/shuffle/short shuffle.mp3",
  "shuffleTroll": "audio/ui/shuffle/troll.mp3",
  "ticketStubsPrint": "audio/ui/ticket-stubs/ticket-stubs-receipt-print.mp3",
  "ticketStubsShred": "audio/ui/ticket-stubs/ticket-stubs-shred.mp3"
};
