# Bootstrap movie-metadata.js from movieDatabase + movieRuntimeMinutes (no OMDb calls).
# Use generate-movie-metadata.ps1 later to enrich with OMDb when quota is available.

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
$MainJs = Join-Path $Root 'app\main.js'
$OutputPath = Join-Path $Root 'app\generated\movie-metadata.js'
$OverridesPath = Join-Path $PSScriptRoot 'poster-overrides.json'

function Parse-MovieListing([string]$Listing) {
    if ($Listing -match '\((\d{4})\)') {
        return @{
            cleanTitle = ($Listing -split '\(')[0].Trim()
            year = $Matches[1]
        }
    }
    return @{ cleanTitle = $Listing.Trim(); year = $null }
}

$mainJs = Get-Content -Raw -Path $MainJs -Encoding UTF8
$dbStart = $mainJs.IndexOf('const movieDatabase = {')
$dbEnd = $mainJs.IndexOf("`n    };", $dbStart)
$dbSection = $mainJs.Substring($dbStart, $dbEnd - $dbStart)
$listings = [regex]::Matches($dbSection, '"([^"]+\(\d{4}\)[^"]*)"') |
    ForEach-Object { $_.Groups[1].Value } |
    Sort-Object -Unique

$rtStart = $mainJs.IndexOf('const movieRuntimeMinutes = {')
$runtimes = @{}
if ($rtStart -ge 0) {
    $rtEnd = $mainJs.IndexOf("`n    };", $rtStart)
    $rtSection = $mainJs.Substring($rtStart, $rtEnd - $rtStart)
    [regex]::Matches($rtSection, '"((?:\\.|[^"\\])+)"\s*:\s*(\d+)') | ForEach-Object {
        $key = $_.Groups[1].Value -replace '\\"', '"'
        $runtimes[$key] = [int]$_.Groups[2].Value
    }
} else {
    $RuntimeMapPath = Join-Path $PSScriptRoot 'runtime-map.js'
    if (Test-Path -LiteralPath $RuntimeMapPath) {
        $rtSection = Get-Content -Raw -LiteralPath $RuntimeMapPath -Encoding UTF8
        [regex]::Matches($rtSection, '"((?:\\.|[^"\\])+)"\s*:\s*(\d+)') | ForEach-Object {
            $key = $_.Groups[1].Value -replace '\\"', '"'
            $runtimes[$key] = [int]$_.Groups[2].Value
        }
    }
}

$overrides = Get-Content -Raw -Path $OverridesPath -Encoding UTF8 | ConvertFrom-Json
$metadata = [ordered]@{}

foreach ($listing in $listings) {
    $parsed = Parse-MovieListing $listing
    $record = [ordered]@{
        Response = 'True'
        Title = $parsed.cleanTitle
        Year = $parsed.year
    }
    if ($runtimes.ContainsKey($listing)) {
        $record['Runtime'] = "$($runtimes[$listing]) min"
    }
    if ($overrides.byListing.PSObject.Properties.Name -contains $listing) {
        $record['Poster'] = $overrides.byListing.$listing
    }
    $metadata[$listing] = $record
}

$lines = @(
    '// Auto-generated by scripts/bootstrap-movie-metadata.ps1 - do not edit by hand.',
    '// Enrich with OMDb: powershell -File scripts/generate-movie-metadata.ps1',
    'window.movieMetadataByListing = {'
)
$sortedKeys = $metadata.Keys | Sort-Object
for ($i = 0; $i -lt $sortedKeys.Count; $i++) {
    $key = $sortedKeys[$i]
    $jsonKey = ($key | ConvertTo-Json -Compress)
    $jsonVal = ($metadata[$key] | ConvertTo-Json -Compress -Depth 6)
    $suffix = if ($i -lt $sortedKeys.Count - 1) { ',' } else { '' }
    $lines += "  $jsonKey`: $jsonVal$suffix"
}
$lines += '};'
$lines += ''
Set-Content -Path $OutputPath -Value ($lines -join "`n") -Encoding UTF8

Write-Host "Bootstrapped $($metadata.Count) listings -> $OutputPath"
Write-Host "Posters in overrides: $(($metadata.Values | Where-Object { $_.Poster }).Count)"
